---
# vars for oci-tokyo-ampere

target_inventory: oci-tokyo-ampere

apt:
  package:
    - certbot
    - fail2ban
    - iptables-persistent
    - mariadb-server
    - nginx
    - openvpn
    - python3-certbot-nginx
    - rsync
    - valkey-server
    - xrdp
  install_state: present

iptables:
  allowed_ports:
    - port: 33999
      protocol: tcp
      comment: ssh
    - port: 80
      protocol: tcp
      comment: http
    - port: 443
      protocol: tcp
      comment: https
    - port: 36778
      protocol: tcp
    - port: 25565,25575
      protocol: tcp
      comment: For Minecraft
    - port: 62656
      protocol: tcp
      comment: For Minecraft Origin
  allowed_input_interfaces: []
  allowed_forward: []
  allowed_nat: []

nginx:
  config_file: nginx.conf
  conf_d_files:
    - mime.conf
    - newrelic.conf
  site_files:
    - blog.romira.dev.conf
    - dev-site.romira.dev.conf
    - librechat.romira.dev.conf
    - obsidian-sync.romira.dev
    - vaultwarden.romira.dev.conf
  enabled_sites:
    - name: blog.romira.dev.conf
      src: ../sites-available/blog.romira.dev.conf
    - name: dev-site.romira.dev.conf
      src: ../sites-available/dev-site.romira.dev.conf
    - name: librechat.romira.dev.conf
      src: /etc/nginx/sites-available/librechat.romira.dev.conf
    - name: obsidian-sync.romira.dev
      src: /etc/nginx/sites-available/obsidian-sync.romira.dev
    - name: vaultwarden.romira.dev.conf
      src: ../sites-available/vaultwarden.romira.dev.conf

postgresql:
  databases:
    - name: blog_romira_dev
      owner: blog
    - name: comiketer
      owner: comiketer
  users:
    - name: blog
      password: "{{ vault_postgresql_blog_password }}"
      db: blog_romira_dev
    - name: comiketer

# Docker data-root migration settings
docker:
  migrate_data_root: true
  data_root: "/mnt/d/docker"
  old_data_root: "/var/lib/docker"
  remove_old_data: false
