docRoot                   $VH_ROOT

index  {
  useServer               0
}

extprocessor jellyfin_backend {
  type                    proxy
  address                 {{ jellyfin.bind_address }}:{{ jellyfin.port }}
  maxConns                1000
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
  persistConn             1
}

websocket /socket {
  address                 {{ jellyfin.bind_address }}:{{ jellyfin.port }}
}

context /.well-known/ {
  location                $VH_ROOT/.well-known
  allowBrowse             1
  enableExpires           0
  addDefaultCharset       off
}

context / {
  type                    proxy
  handler                 jellyfin_backend
  allowBrowse             0
  addDefaultCharset       off
  enableIpGeo             0
  extraHeaders            <<<END_extraHeaders
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Host "{{ item.domains | first }}"
RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}e"
END_extraHeaders
}

rewrite  {
  enable                  1
  RewriteCond             %{REQUEST_URI} !^/\.well-known/
  RewriteCond             %{SERVER_PORT} 80
  RewriteRule             ^(.*)$ {{ jellyfin.published_server_url }}/$1 [R=301,L]
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/{{ item.domains | first }}/privkey.pem
  certFile                /etc/letsencrypt/live/{{ item.domains | first }}/fullchain.pem
  certChain               1
}
