---
- name: Update msys2 packages
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "pacman -Syu --noconfirm"

- name: Install msys2 packages
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "pacman -S --noconfirm {{ msys2.packages | join(' ') }}"

- name: Set login shell to {{ msys2.login_shell }}
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "sed -i -e 's/LOGINSHELL=[ba]*[z]*sh/LOGINSHELL={{ msys2.login_shell }}/' /msys2_shell.cmd"

- name: Set MSYS2 home directory to Windows home
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "sed -i -e 's/^db_home:.*/db_home: windows/' /etc/nsswitch.conf"

- name: Enable MSYS2_PATH_TYPE=inherit
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "sed -i -e 's/^rem set MSYS2_PATH_TYPE=inherit/set MSYS2_PATH_TYPE=inherit/' /msys2_shell.cmd"
