---
- name: Clone tmux-thumbs repository
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "git clone https://github.com/fcsonline/tmux-thumbs ~/.tmux/plugins/tmux-thumbs 2>/dev/null || git -C ~/.tmux/plugins/tmux-thumbs pull"

- name: Update tmux-thumbs dependencies for MSYS2 compatibility
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "cd ~/.tmux/plugins/tmux-thumbs && cargo update"

- name: Build tmux-thumbs
  ansible.windows.win_shell: >
    C:\Users\{{ ansible_user }}\scoop\apps\msys2\current\usr\bin\bash.exe -lc
    "cd ~/.tmux/plugins/tmux-thumbs && cargo build --release"
