server {
    server_name dev-site.romira.dev; # managed by Certbot    
    root /var/www/dev-site;

    client_max_body_size 1000g;

    location /mods {
	alias /usr/local/minecraft/mods/;
	autoindex on;
    }

    location / {
        try_files $uri $uri/ /index.html;
        # 基本はキャッシュしない
        set $do_not_cache 1;
        # 画像のみキャッシュさせる
        if ($uri ~* "\.(jpg|jpeg|png|gif|css|js|ico)$") {
            set $do_not_cache 0;
        }
        proxy_no_cache $do_not_cache;

        # キャッシュの検索
        proxy_cache_bypass $do_not_cache;
        # バックエンド no-cache を無視
        proxy_ignore_headers Cache-Control;
        # キャッシュのキーゾーンを指定
        proxy_cache cache_key;
        # キャッシュの有効時間を指定
        proxy_cache_valid 200 302 60m;
        proxy_cache_valid 404 10m;
        # キャッシュのステータスヘッダーを追加
        add_header X-Cache-Status $upstream_cache_status;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dev-site.romira.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dev-site.romira.dev/privkey.pem; # managed by Certbot

}
server {
    if ($host = dev-site.romira.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name dev-site.romira.dev;
    listen 80;
    return 404; # managed by Certbot


}
